site_name: Azure Professional Services SOPs
theme:
  name: material
  palette:
    primary: indigo
  features:
    - search
    - navigation.tabs
    - navigation.top

nav:
  - Home: index.md
  - Networking:
      - Hub & Spoke Topology: networking/sop-virtual-networking-hub-spoke.md

plugins:
  - search

markdown_extensions:
  - admonition
  - tables
  - pymdownx.tabbed
  - pymdownx.superfences

repo_url: https://github.com/chetanp201/azure-sops
